# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubetuser',
            name='nick',
        ),
        migrations.AddField(
            model_name='ubetuser',
            name='nome_completo',
            field=models.CharField(default='meunomecompletogg', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubetuser',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
