# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubetuser',
            old_name='usuario',
            new_name='usuario_django',
        ),
    ]
