# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_of_death',
            field=models.DateTimeField(null=True),
        ),
    ]
