# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubet', '0002_auto_20160414_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubetuser',
            name='usuario_django',
        ),
        migrations.AddField(
            model_name='ubetuser',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubetuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
