# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubet', '0002_group_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubet_user',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
