# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubet', '0003_auto_20160422_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubet_user',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
