# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubet', '0003_auto_20160415_2109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group_link',
            unique_together=set([('user', 'group'), ('group', 'position')]),
        ),
    ]
