# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubet', '0003_auto_20160414_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ubet_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('creditos', models.FloatField(default=0)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ubetuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='ubetUser',
        ),
    ]
