# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubet', '0004_auto_20160415_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[(b'END', b'FINISHED'), (b'ABORT', b'CANCELED'), (b'WAIT', b'WAITING')], default=b'WAITING', max_length=50),
        ),
    ]
